<a href="https://colab.research.google.com/github/nachi0106/Python-Workshop/blob/master/Day1_Session2_Exercise_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pandas  and Numpy Exercise 20 Questions 

#Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10000

In [ ]:
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [ ]:
import pandas as pd
l=([i for i in range(1000,20000) if i%5==0])
ds = pd.Series(l) 
print(ds)

0        1000
1        1005
2        1010
3        1015
4        1020
        ...  
3795    19975
3796    19980
3797    19985
3798    19990
3799    19995
Length: 3800, dtype: int64


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
l1=([i for i in range(0,101) if i%2==0])
ds1 = pd.Series(l1)
l2=([i for i in range(0,100) if i%2!=0])
ds2 = pd.Series(l2)
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0       1.0
1       5.0
2       9.0
3      13.0
4      17.0
5      21.0
6      25.0
7      29.0
8      33.0
9      37.0
10     41.0
11     45.0
12     49.0
13     53.0
14     57.0
15     61.0
16     65.0
17     69.0
18     73.0
19     77.0
20     81.0
21     85.0
22     89.0
23     93.0
24     97.0
25    101.0
26    105.0
27    109.0
28    113.0
29    117.0
30    121.0
31    125.0
32    129.0
33    133.0
34    137.0
35    141.0
36    145.0
37    149.0
38    153.0
39    157.0
40    161.0
41    165.0
42    169.0
43    173.0
44    177.0
45    181.0
46    185.0
47    189.0
48    193.0
49    197.0
50      NaN
dtype: float64
Subtract two Series:
0    -1.0
1    -1.0
2    -1.0
3    -1.0
4    -1.0
5    -1.0
6    -1.0
7    -1.0
8    -1.0
9    -1.0
10   -1.0
11   -1.0
12   -1.0
13   -1.0
14   -1.0
15   -1.0
16   -1.0
17   -1.0
18   -1.0
19   -1.0
20   -1.0
21   -1.0
22   -1.0
23   -1.0
24   -1.0
25   -1.0
26   -1.0
27   -1.0
28   -1.0
29   -1.0
30   -1.0
31   -1.0
32   -1.0
33   -

#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
import pandas as pd
l1=([i for i in range(0,1000) if i%7==0])
d1 = pd.Series(l1)
l2=([i for i in range(0,1000) if i%11==0])
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   True
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87   

#Write a Pandas program to convert a NumPy array to a Pandas series. 
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]


In [ ]:
import numpy as np
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
np_array = np.array(l1)
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190  200  210  220  230  240  250  260  270
  280  290  300  310  320  330  340  350  360  370  380  390  400  410
  420  430  440  450  460  470  480  490  500  510  520  530  540  550
  560  570  580  590  600  610  620  630  640  650  660  670  680  690
  700  710  720  730  740  750  760  770  780  790  800  810  820  830
  840  850  860  870  880  890  900  910  920  930  940  950  960  970
  980  990 1000]
Converted Pandas series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


#Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]



In [ ]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)



Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


#Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
# value and condtion :  Subset 1 :numbers divisable by 7  Subset 2 : numbers divisable by 5


In [ ]:
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
s = pd.Series(l1)
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n=7
new_s = s[s%n==0]
print(new_s)
n=5
new_s = s[s%n==0]
print(new_s)


Original Data Series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64

Subset of the above Data Series:
0       0
7      70
14    140
21    210
28    280
35    350
42    420
49    490
56    560
63    630
70    700
77    770
84    840
91    910
98    980
dtype: int64
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000



In [ ]:
import pandas as pd
l=[]
for val in range(0,1001):
  if val > 1: 
        for n in range(2, val//2 + 2): 
            if (val % n) == 0: 
                break
            else: 
                if n == val//2 + 1: 
                    l.append(val)
s = pd.Series(data = l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0        3
1        5
2        7
3       11
4       13
      ... 
162    971
163    977
164    983
165    991
166    997
Length: 167, dtype: int64
Mean of the said Data Series:
455.8383233532934
Standard deviation of the said Data Series:
297.0201672063572


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}



In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields

In [ ]:
import pandas as pd
df = pd.read_csv('movies.csv')
#Display the first 10 rows
small_df = df[['rating','budget','year']]
result = small_df.head(10)
print("First 10 rows of the DataFrame:")
print(result)




First 10 rows of the DataFrame:
   rating  budget  year
0       4  7 lack  2017
1       4   8lack  2018
2       4  9 lack  2019
3       4   7lack  2012
4       4  8 lack  2013
5       4  9 lack  2015
6       5   3lack  2020
7       5   4lack  2010
8       5  10lack  2013
9       5  11lack  2014


#Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields (movies.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movies.csv')
small_df = df[['rating','budget','year']]
third_movie = small_df.iloc[6]
print("Details of the 7th moviee:")
print(third_movie)


Details of the 7th moviee:
rating        5
budget    3lack
year       2020
Name: 6, dtype: object


#Write a Pandas program to sort the DataFrame based on title_year from dataset of movies.csv for any particular three fields 

In [ ]:
import pandas as pd
df = pd.read_csv('movies.csv')
small_df = df[['rating','budget','year']]
result = small_df.sort_values('year')
print("DataFrame based on release date.")
print(result)




DataFrame based on release date.
    rating  budget  year
7        5   4lack  2010
3        4   7lack  2012
4        4  8 lack  2013
8        5  10lack  2013
9        5  11lack  2014
5        4  9 lack  2015
10       5  12lack  2015
11       5  20lack  2016
0        4  7 lack  2017
12       5  30lack  2017
1        4   8lack  2018
2        4  9 lack  2019
6        5   3lack  2020


#Write a Pandas program to sort the DataFrame based on country  and language from dataset of  movies.csv

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies.csv')
print("sorted by country")
result = df.sort_values('country')
print(result)
print("sorted by lang")
result = df.sort_values('language')
print(result)


sorted by country
    reviews language country  budget  rating  year    actor
2         2    hindi     ast  9 lack       4  2019     yash
0         4      eng     end  7 lack       4  2017   salman
5         3      eng     end  9 lack       4  2015   sudeep
1         3  kannada     ind   8lack       4  2018   vijaya
6         5  kannada     ind   3lack       5  2020     yash
7         5      eng     ind   4lack       5  2010  jaggesh
8         4  kannada     ind  10lack       5  2013    singh
9         3      eng     ind  11lack       5  2014     amit
10        2      eng     ind  12lack       5  2015     amog
11        2      eng     ind  20lack       5  2016  radhika
12        2      eng     ind  30lack       5  2017   bavana
4         4    telgu  russia  8 lack       4  2013   roshan
3         5    tamil     usa   7lack       4  2012    arjun
sorted by lang
    reviews language country  budget  rating  year    actor
0         4      eng     end  7 lack       4  2017   salman
5      

#Write a Pandas program to get the details of the movies record number divisable by 5 of the DataFrame (movies.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movies.csv')
result = df[(df['record'] %5==0)]
print("Movies record num divisible by 5 are")
print(result.head())

Movies record num divisible by 5 are
   reviews language country  budget  rating  year    actor  record
0        4      eng     end  7 lack       4  2017   salman    2000
1        3  kannada     ind   8lack       4  2018   vijaya    3000
4        4    telgu  russia  8 lack       4  2013   roshan    4545
5        3      eng     end  9 lack       4  2015   sudeep    2525
7        5      eng     ind   4lack       5  2010  jaggesh    2000


#Write a Pandas program to find the mean and standard deviation, maximum and minimum of the data of  50 students Python marks stored in a CSV file called Python_mark.csv( you have to create the file yourself like rollno,mark for 50 records)



In [ ]:
import pandas as pd
df = pd.read_csv('Python_marks.csv')
mean1 = df['marks'].mean()
max1 = df['marks'].max()
min1 = df['marks'].min()
std1 = df['marks'].std() 
print("file content: ",df)
print ('Mean : ' + str(mean1))
print ('S.D: ' + str(std1))
print ('Minimum : ' + str(min1))
print ('Maximum : ' + str(max1))



file content:      rollnum  marks
0        66     30
1        67     29
2        68     28
3        69     27
4        70     25
5        71     24
6        72     23
7        73     22
8        74     21
9        75     20
10       76     25
11       77     26
12       78     29
13       79     17
14       82     18
15       22     19
16       23     14
17       28     15
18       25     16
19       24     12
20       89     10
21       90      9
22       91      8
23       92      6
24       93     25
25       94     26
26       95     27
27       96     27
28       97     28
29       98     29
30       99     29
31      100     29
32      101     24
33      102     22
34      103     21
35      104     22
36      105     25
37      106     21
38      107     17
39      108     18
40      110     19
41      111     20
42      112     20
43      113     20
44      114     19
45      115     22
46      116     23
47      117     27
48      118     28
Mean : 21.653061224489797
S.D: 6.00

#Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the  array and store them into a variable.



In [ ]:
import numpy as np
x = np.random.random((4,4))
print(x)
print("2nd and 3rd rows of the above array:")
y= x[1:3, :]
print(y)


[[0.14085316 0.4320774  0.51789052 0.79541724]
 [0.58598354 0.47371213 0.98456639 0.80789855]
 [0.6640794  0.68702337 0.41840694 0.73953326]
 [0.70740571 0.78674331 0.99118271 0.86779108]]
2nd and 3rd rows of the above array:
[[0.58598354 0.47371213 0.98456639 0.80789855]
 [0.6640794  0.68702337 0.41840694 0.73953326]]


#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.20371969 0.07708205 0.97255134 0.17340541 0.427097   0.82101095
  0.45877201 0.01657894 0.34512389 0.17283362]
 [0.23674856 0.85253731 0.62485455 0.90183104 0.15762001 0.83220096
  0.27314281 0.86217061 0.65820531 0.66611101]
 [0.39024645 0.49766387 0.63047822 0.53637549 0.60967244 0.70258486
  0.66194689 0.03069068 0.58703993 0.56957965]
 [0.32902757 0.43703056 0.87497356 0.26614585 0.03400898 0.43911579
  0.70461219 0.32967789 0.243564   0.18888512]
 [0.17629927 0.5353419  0.14117532 0.8239303  0.63112121 0.46219268
  0.82773888 0.30863059 0.04480681 0.88922045]
 [0.21562054 0.5199983  0.90672161 0.57893255 0.51840983 0.1472263
  0.57372005 0.08368321 0.72995345 0.41455205]
 [0.58346474 0.66126708 0.77172542 0.28313841 0.73299358 0.46509958
  0.36912959 0.98284821 0.69293908 0.91587107]
 [0.10494319 0.71540838 0.99886069 0.97370183 0.03857738 0.54274295
  0.29714534 0.73175944 0.9239467  0.96677341]
 [0.85136726 0.71362925 0.86850948 0.61981856 0.50534469 0.809872

#Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[108 263 229 124 266 230 272 150]


#Write a NumPy program to create a random integer nos of size 20 and sort it.

In [ ]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)



[15 17  7 12 11  5 14  2  9 18  8  6 19  4 10  3 16  1  0 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
